language: objective-c
osx_image: xcode9.3
script:
    - xcodebuild clean test -project RHPlaceholder/RHPlaceholder.xcodeproj -scheme RHPlaceholder -destination "platform=iOS Simulator,name=iPhone 7,OS=11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet